### ISSUE TITLE
Update to 1.20.6 Please

### ISSUE THREAD

**Issue by sternschnaube** [PolymerPorts/trinkets#3]

**Comment by Patbox** [comment]
I'm waiting for it too...

Once https://github.com/emilyploszaj/trinkets/pull/310 is merged and released, I will update the port. I don't want to do it early, as my goal isn't to diverge from upstream and there might be changes after the pr gets merged.

**Comment by sternschnaube** [comment]
Thanks, I was not thinking about that Trinket hasn't updated yet.
