### ISSUE TITLE
No Slots available, 1.21

### ISSUE THREAD

**Issue by Stein-N** [PolymerPorts/trinkets#5]
I added the latest version of Polymer and Polymer Trinkets but cant access any of the slots.
Is there an setting i miss?

Also set me op, but even then it is fully blocked

![image](https://github.com/PolymerPorts/trinkets/assets/128091790/8e57c4b7-bbfb-4867-aa25-5386a32af2c0)

**Comment by Patbox** [comment]
Mods need to define/enable slots to be used. By default trinkets doesn't do anything by itself

**Comment by Stein-N** [comment]
Ahh ok, is also enough to add a data pack that adds the elytra to the back slot?

**Comment by Patbox** [comment]
It won't make it work, you need extra mod for that.

**Comment by Stein-N** [comment]
Ok, then I will wait since some mods and trinkets get updated to the latest version. Thanks.
